// vue-sdk-demo/src/components/CurrentCategories.vue
<script setup lang="ts">
import type { TCategoriesTree } from '@mercura-aps/frontend-form-sdk';
import { useFormCategories } from '../form-sdk';

interface Props {
  category: TCategoriesTree;
}

defineProps<Props>();

const setCurrentCategory = useFormCategories(
  state => state.strategies.breadcrumbs({ homeText: "Home" }).setCurrentCategory
);
</script>

<template>
  <button
    v-for="category in category.subcategories"
    :key="category.id"
    class="rounded-md bg-blue-500 p-2 text-white"
    @click="setCurrentCategory(category)"
  >
    {{ category.name }}
  </button>
</template>

// react-sdk-demo/src/components/CurrentCategories.tsx
import type { TCategoriesTree } from "@mercura-aps/frontend-form-sdk";
import { useFormCategories } from "../form-sdk";

export default function CurrentCategories({
    category,
}: {
    category: TCategoriesTree;
}) {
    const setCurrentCategory = useFormCategories(
        (state) =>
            state.strategies.breadcrumbs({ homeText: "Home" })
                .setCurrentCategory
    );
    return category.subcategories?.map((category) => (
        <button
            className="rounded-md bg-blue-500 p-2 text-white"
            key={category.id}
            onClick={() => {
                setCurrentCategory(category);
            }}
        >
            {category.name}
        </button>
    ));
}
