// vue-sdk-demo/src/components/FormSelection.vue
<script setup lang="ts">
import { ref } from 'vue';
import FormSelectionBreadcrumb from './FormSelectionBreadcrumb.vue';
import FormSelectionFilter from './FormSelectionFilter.vue';

const strategy = ref<"breadcrumb" | "filter">("breadcrumb");
</script>

<template>
  <div>
    <div class="flex gap-2">
      <label class="flex items-center gap-2">
        Breadcrumb
        <input
          type="radio"
          name="strategy"
          value="breadcrumb"
          :checked="strategy === 'breadcrumb'"
          @change="strategy = 'breadcrumb'"
        />
      </label>
      <label class="flex items-center gap-2">
        Filter
        <input
          type="radio"
          name="strategy"
          value="filter"
          :checked="strategy === 'filter'"
          @change="strategy = 'filter'"
        />
      </label>
    </div>
    <FormSelectionBreadcrumb v-if="strategy === 'breadcrumb'" />
    <FormSelectionFilter v-else />
  </div>
</template>

// react-sdk-demo/src/components/FormSelection.tsx
import { useState } from "react";
import FormSelectionBreadcrumb from "./FormSelectionBreadcrumb";
import FormSelectionFilter from "./FormSelectionFilter";

export default function FormSelection() {
    const [strategy, setStrategy] = useState<"breadcrumb" | "filter">(
        "breadcrumb"
    );

    return (
        <div>
            <div className="flex gap-2">
                <label className="flex items-center gap-2">
                    Breadcrumb
                    <input
                        type="radio"
                        name="strategy"
                        value="breadcrumb"
                        checked={strategy === "breadcrumb"}
                        onChange={() => setStrategy("breadcrumb")}
                    />
                </label>
                <label className="flex items-center gap-2">
                    Filter
                    <input
                        type="radio"
                        name="strategy"
                        value="filter"
                        checked={strategy === "filter"}
                        onChange={() => setStrategy("filter")}
                    />
                </label>
            </div>
            {strategy === "breadcrumb" ? (
                <FormSelectionBreadcrumb />
            ) : (
                <FormSelectionFilter />
            )}
        </div>
    );
}
