// react-sdk-demo/src/components/ConfigsNavigation.tsx
import { Link, useParams } from "react-router";
import { useConfigs } from "../form-sdk";

export default function ConfigsNavigation() {
    const configId = useParams()?.configId;
    const previousConfigId = useConfigs((state) => {
        const currentConfigIndex = state.configs.findIndex(
            (config) => config.id === Number(configId)
        );
        return state.configs[currentConfigIndex - 1]?.id;
    });
    const nextConfigId = useConfigs((state) => {
        const currentConfigIndex = state.configs.findIndex(
            (config) => config.id === Number(configId)
        );
        return state.configs[currentConfigIndex + 1]?.id;
    });
    return (
        <div className="flex w-full gap-2">
            {previousConfigId && (
                <Link
                    className="my-8 flex rounded-md bg-blue-500 p-2 text-white"
                    to={`/config/${previousConfigId}`}
                >
                    Previous
                </Link>
            )}
            {nextConfigId ? (
                <Link
                    className="my-8 flex rounded-md bg-blue-500 p-2 text-white"
                    to={`/config/${nextConfigId}`}
                >
                    Next
                </Link>
            ) : (
                <Link
                    className="my-8 flex rounded-md bg-blue-500 p-2 text-white"
                    to={"/checkout"}
                >
                    Checkout
                </Link>
            )}
        </div>
    );
}

// vue-sdk-demo/src/components/ConfigsNavigation.vue
<script setup lang="ts">
import { useConfigs } from '../form-sdk';
import { useRoute } from 'vue-router';
import { computed } from 'vue';

const route = useRoute();
const configs = useConfigs(state => state.configs);

const currentConfigIndex = computed(() => configs.value.findIndex(config => config.id === Number(route.params.configId)));
const previousConfigId = computed(() => configs.value[currentConfigIndex.value - 1]?.id);
const nextConfigId = computed(() => configs.value[currentConfigIndex.value + 1]?.id);

</script>

<template>
    <div class="flex w-full gap-2">
        <router-link v-if="previousConfigId" :to="`/config/${previousConfigId}`" class="my-8 flex rounded-md bg-blue-500 p-2 text-white">
            Previous
        </router-link>
        <router-link v-if="nextConfigId" :to="`/config/${nextConfigId}`" class="my-8 flex rounded-md bg-blue-500 p-2 text-white">
            Next
        </router-link>
        <router-link v-else to="/checkout" class="my-8 flex rounded-md bg-blue-500 p-2 text-white">
            Checkout
        </router-link>
    </div>
</template>
