// react-sdk-demo/src/components/DraftNameInput.tsx
import { useSubmit } from "../form-sdk";

export default function DraftNameInput() {
    const draftName = useSubmit((state) => state.draftName);
    const setDraftName = useSubmit((state) => state.setDraftName);
    return (
        <input
            type="text"
            value={draftName}
            onChange={(e) => setDraftName(e.target.value)}
        />
    );
}

// vue-sdk-demo/src/components/DraftNameInput.vue
<script setup lang="ts">
import { useSubmit } from '../form-sdk';

const draftName = useSubmit(state => state.draftName);
const setDraftName = useSubmit(state => state.setDraftName);
</script>

<template>
  <input
    type="text"
    :value="draftName"
    @input="setDraftName(($event.target as HTMLInputElement).value)"
  />
</template>
