// react-sdk-demo/src/components/ElementDisplay.tsx
import type { TElement } from "@mercura-aps/frontend-form-sdk";
import {
    useFormByCurrentConfigId,
    useNumberFormatter,
    useValuesByCurrentConfigId,
} from "../form-sdk";
import MessageDisplay from "./MessageDisplay";

export default function ElementDisplay({ element }: { element: TElement }) {
    const elementValue = useValuesByCurrentConfigId(
        (state) => state.values[element.id]
    );
    const handleChangeInput = useValuesByCurrentConfigId(
        (state) => state.handleChangeInput
    );
    const resolveOptionPrice = useNumberFormatter((state) =>
        state.getResolveOptionPrice()
    );

    const messages = useFormByCurrentConfigId(
        (state) => state.messages.elements[element.id]
    );
    const renderOptions = (() => {
        if (!("options" in element)) {
            return null;
        }

        if (element.type === "select") {
            return (
                <select
                    value={elementValue?.[0] ?? ""}
                    onChange={(e) => {
                        handleChangeInput?.({
                            type: element.type,
                            elementId: element.id,
                            optionIdOrValue: e.target.value,
                        });
                    }}
                >
                    {element.options.map((option) => (
                        <option key={option.id} value={option.id}>
                            {option.name} -{" "}
                            {resolveOptionPrice?.({
                                option,
                                element,
                                includedText: "included",
                            })}
                        </option>
                    ))}
                </select>
            );
        }

        return element.options.map((option) => (
            <label
                key={option.id}
                className="flex items-center gap-2 rounded-md border p-2"
            >
                <img src={option.image ?? ""} className="h-10 w-10" />
                {option.name} -{" "}
                {resolveOptionPrice?.({
                    option,
                    element,
                    includedText: "included",
                })}
                <input
                    type={element.type}
                    value={option.id}
                    checked={elementValue?.includes(option.id.toString())}
                    onChange={() =>
                        handleChangeInput?.({
                            type: element.type,
                            elementId: element.id,
                            optionIdOrValue: option.id,
                        })
                    }
                />
            </label>
        ));
    })();

    const renderInput = (() => {
        if ("options" in element) {
            return null;
        }

        return (
            <input
                type={element.type}
                className="rounded-md border p-2"
                value={elementValue?.[0] ?? (element.type === "text" ? "" : 0)}
                onChange={(e) => {
                    handleChangeInput?.({
                        type: element.type,
                        elementId: element.id,
                        optionIdOrValue: e.target.value,
                    });
                }}
            />
        );
    })();

    return (
        <div className="relative flex flex-1 flex-col gap-2 rounded-md border p-2">
            {messages?.length ? (
                <div className="sticky top-0">
                    <div className="flex flex-col gap-1">
                        {messages.map((message, index) => (
                            <MessageDisplay
                                key={`${message.type}-${message.message}-${index}`}
                                message={message}
                            />
                        ))}
                    </div>
                </div>
            ) : null}
            <div>
                {element.label}{" "}
                {element.state === "required" && (
                    <span className="text-red-500">*</span>
                )}
            </div>
            {renderInput ?? renderOptions}
        </div>
    );
}

// vue-sdk-demo/src/components/ElementDisplay.vue
<script setup lang="ts">
import type { TElement } from '@mercura-aps/frontend-form-sdk';
import { useRoute } from 'vue-router';
import { useFormByCurrentConfigId, useNumberFormatter, useValuesByCurrentConfigId } from '../form-sdk';
import MessageDisplay from './MessageDisplay.vue';

const props = defineProps<{ element: TElement }>();

const values = useValuesByCurrentConfigId(state => state.values);
const handleChangeInput = useValuesByCurrentConfigId(state => state.handleChangeInput);
const resolveOptionPrice = useNumberFormatter(state => state.getResolveOptionPrice());
const route = useRoute();
const configId = Number(route.params.configId);

const hasOptions = (element: TElement): element is TElement & { options: any[] } => {
    return 'options' in element;
};

const messages = useFormByCurrentConfigId(state => state.messages.elements[props.element.id]);

</script>

<template>
    <div class="flex flex-1 flex-col gap-2 rounded-md border p-2 relative">
        <div v-if="messages?.length" class="sticky top-0 flex flex-col gap-1">
            <MessageDisplay
                v-for="(message, index) in messages"
                :key="`${message.type}-${message.message}-${index}`"
                :message="message"
            />
        </div>
        <div>
            {{ props.element.label }} {{ props.element.state === 'required' ? '*' : '' }}
        </div>
        
        <div v-if="hasOptions(element)">
            <select
                v-if="element.type === 'select'"
                :value="values?.[element.id]?.[0] ?? ''"
                @change="handleChangeInput?.({ type: element.type, elementId: element.id, optionIdOrValue: ($event.target as HTMLSelectElement).value })"
            >
                <option v-for="option in element.options" :key="option.id" :value="option.id">
                    {{ option.name }} - 
                    {{ resolveOptionPrice?.({ element, option, includedText: 'included' }) }}
                </option>
            </select>
            
            <label v-else v-for="option in element.options" :key="option.id" class="flex items-center gap-2 rounded-md border p-2">
                <img :src="option.image ?? ''" class="h-10 w-10" />
                {{ option.name }} - 
                {{ resolveOptionPrice?.({ element, option, includedText: 'included' }) }}
                <input
                    :type="element.type"
                    :value="option.id"
                    :checked="values?.[element.id]?.includes(option.id.toString())"
                    @change="handleChangeInput?.({ type: element.type, elementId: element.id, optionIdOrValue: option.id })"
                />
            </label>
        </div>

        <input
            v-else
            :type="element.type"
            class="rounded-md border p-2"
            :value="values?.[element.id]?.[0] ?? (element.type === 'text' ? '' : 0)"
            @change="handleChangeInput?.({ type: element.type, elementId: element.id, optionIdOrValue: ($event.target as HTMLInputElement).value })"
        />
    </div>
</template>
