// react-sdk-demo/src/components/FormSelectionFilter.tsx
import CurrentCategoriesFilter from "./CurrentCategoriesFilter";
import FormCards from "./FormCards";

export default function FormSelectionFilter() {
    return (
        <div>
            <h1>Forms</h1>
            <CurrentCategoriesFilter />
            <div className="grid grid-cols-3 gap-2">
                <FormCards />
            </div>
        </div>
    );
}

// vue-sdk-demo/src/components/FormSelectionFilter.vue
<script setup lang="ts">
import CurrentCategoriesFilter from './CurrentCategoriesFilter.vue';
import FormCards from './FormCards.vue';
</script>

<template>
  <div>
    <h1>Forms</h1>
    <CurrentCategoriesFilter />
    <div class="grid grid-cols-3 gap-2">
      <FormCards />
    </div>
  </div>
</template>
