// react-sdk-demo/src/pages/RequestCopy.tsx
import { useEffect, useState } from "react";
import { Navigate, useParams } from "react-router";
import { useSubmit } from "../form-sdk";

export default function RequestCopy() {
    const requestCopyId = useParams()?.requestCopyId;
    const [isLoading, setIsLoading] = useState<boolean>(true);
    const openFromRequestCopy = useSubmit((state) => state.openFromRequestCopy);
    useEffect(() => {
        if (requestCopyId) {
            openFromRequestCopy(Number(requestCopyId)).then(() =>
                setIsLoading(false)
            );
        }
    }, [requestCopyId, openFromRequestCopy]);

    if (isLoading) {
        return <div>Loading...</div>;
    }

    return <Navigate to={"/"} />;
}

// vue-sdk-demo/src/pages/RequestCopy.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useSubmit } from '../form-sdk';

const route = useRoute();
const router = useRouter();
const requestCopyId = route.params.requestCopyId as string;
const isLoading = ref(true);
const openFromRequestCopy = useSubmit(state => state.openFromRequestCopy);

onMounted(async () => {
  if (requestCopyId) {
    await openFromRequestCopy.value(Number(requestCopyId));
    isLoading.value = false;
  }
});

if (!isLoading.value) {
  router.push('/');
}
</script>

<template>
  <div v-if="isLoading">Loading...</div>
</template>
